
START TRANSACTION ISOLATION LEVEL SERIALIZABLE, READ WRITE;

CREATE SCHEMA ORMModel1 DEFAULT CHARACTER SET UTF8;

SET SCHEMA 'ORMMODEL1';

CREATE TABLE ORMModel1.Moon
(
	moonName CHARACTER VARYING(20) NOT NULL,
	mass DECIMAL(19,0),
	planetName CHARACTER VARYING(20),
	CONSTRAINT Moon_PK PRIMARY KEY(moonName),
	CONSTRAINT Moon_UC UNIQUE(mass)
);

CREATE TABLE ORMModel1.Planet
(
	planetName CHARACTER VARYING(20) NOT NULL,
	mass DECIMAL(19,0),
	hasADistanceStarName CHARACTER VARYING(20),
	orbitsStarName CHARACTER VARYING(20),
	CONSTRAINT Planet_PK PRIMARY KEY(planetName),
	CONSTRAINT Planet_UC UNIQUE(mass)
);

CREATE TABLE ORMModel1.Star
(
	starName CHARACTER VARYING(20) NOT NULL,
	blackholeId INTEGER,
	CONSTRAINT Star_PK PRIMARY KEY(starName)
);

CREATE TABLE ORMModel1.Abidstar
(
	abidstarName CHARACTER VARYING(20) NOT NULL,
	CONSTRAINT Abidstar_PK PRIMARY KEY(abidstarName)
);

CREATE TABLE ORMModel1.Ruckerstar
(
	ruckerstarName CHARACTER VARYING(20) NOT NULL,
	CONSTRAINT Ruckerstar_PK PRIMARY KEY(ruckerstarName)
);

CREATE TABLE ORMModel1.Blackhole
(
	blackholeId INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
	CONSTRAINT Blackhole_PK PRIMARY KEY(blackholeId)
);

ALTER TABLE ORMModel1.Moon ADD CONSTRAINT Moon_FK FOREIGN KEY (planetName) REFERENCES ORMModel1.Planet (planetName) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ORMModel1.Planet ADD CONSTRAINT Planet_FK1 FOREIGN KEY (orbitsStarName) REFERENCES ORMModel1.Star (starName) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ORMModel1.Planet ADD CONSTRAINT Planet_FK2 FOREIGN KEY (hasADistanceStarName) REFERENCES ORMModel1.Star (starName) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ORMModel1.Star ADD CONSTRAINT Star_FK FOREIGN KEY (blackholeId) REFERENCES ORMModel1.Blackhole (blackholeId) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ORMModel1.Abidstar ADD CONSTRAINT Abidstar_FK FOREIGN KEY (abidstarName) REFERENCES ORMModel1.Star (starName) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ORMModel1.Ruckerstar ADD CONSTRAINT Ruckerstar_FK FOREIGN KEY (ruckerstarName) REFERENCES ORMModel1.Star (starName) ON DELETE RESTRICT ON UPDATE RESTRICT;

COMMIT WORK;
