
CREATE TABLE Moon
(
	moonName VARCHAR(20) NOT NULL,
	mass DECIMAL(19,0),
	planetName VARCHAR(20),
	CONSTRAINT Moon_PK PRIMARY KEY(moonName),
	CONSTRAINT Moon_UC UNIQUE(mass)
);

CREATE TABLE Planet
(
	planetName VARCHAR(20) NOT NULL,
	mass DECIMAL(19,0),
	hasADistanceStarName VARCHAR(20),
	orbitsStarName VARCHAR(20),
	CONSTRAINT Planet_PK PRIMARY KEY(planetName),
	CONSTRAINT Planet_UC UNIQUE(mass)
);

CREATE TABLE Star
(
	starName VARCHAR(20) NOT NULL,
	blackholeId INT,
	CONSTRAINT Star_PK PRIMARY KEY(starName)
);

CREATE TABLE Abidstar
(
	abidstarName VARCHAR(20) NOT NULL,
	CONSTRAINT Abidstar_PK PRIMARY KEY(abidstarName)
);

CREATE TABLE Ruckerstar
(
	ruckerstarName VARCHAR(20) NOT NULL,
	CONSTRAINT Ruckerstar_PK PRIMARY KEY(ruckerstarName)
);

CREATE TABLE Blackhole
(
	blackholeId INT AUTO_INCREMENT NOT NULL,
	CONSTRAINT Blackhole_PK PRIMARY KEY(blackholeId)
);

ALTER TABLE Moon ADD CONSTRAINT Moon_FK FOREIGN KEY (planetName) REFERENCES Planet (planetName) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE Planet ADD CONSTRAINT Planet_FK1 FOREIGN KEY (orbitsStarName) REFERENCES Star (starName) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE Planet ADD CONSTRAINT Planet_FK2 FOREIGN KEY (hasADistanceStarName) REFERENCES Star (starName) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE Star ADD CONSTRAINT Star_FK FOREIGN KEY (blackholeId) REFERENCES Blackhole (blackholeId) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE Abidstar ADD CONSTRAINT Abidstar_FK FOREIGN KEY (abidstarName) REFERENCES Star (starName) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE Ruckerstar ADD CONSTRAINT Ruckerstar_FK FOREIGN KEY (ruckerstarName) REFERENCES Star (starName) ON DELETE RESTRICT ON UPDATE RESTRICT;
